[package]
name = "documents"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.6" }
chrono = "0.4.41"
clap = { version = "4.5", features = ["derive"] }
dotenvy = "0.15"
octocrab = "0.19"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.4", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[dev-dependencies]
mockito = "0.31"
